debug: true
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: nw-admin
  freemarker:
    cache: false
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  jpa:
    properties:
      dialect: org.hibernate.dialect.Oracle10gDialect
    database: oracle
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: ca
    password: ciecc2020
  main:
    allow-bean-definition-overriding: true

#spring.devtools.restart.exclude: WEB-INF/**

server:
  port: 8092
  servlet:
    session:
      timeout: 3600
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://localhost:8091/eureka/
