spring:
  application:
    name: nw-oauth2-service
  profiles:
    active: dev

server:
    port: 8080
    connection-timeout: 600000
    servlet:
      context-path: /ca

security:
    ignored: /resources/**, /webjars/**
