server:
  port: 8094

spring:
  application:
    name: nw-gateway

#--------------------eureka---------------------
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/

#--------------------Zuul-----------------------
zuul:
  routes:
    nw-oauth2-service:
      stripPrefix: false
      path: /ca/**
#    nw-test-service:
#      stripPrefix: false
#      path: /test/**
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  add-proxy-headers: true

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3500