server:
  port: 8082
  servlet:
    context-path: /test
    session:
      timeout: 1m

security:
  oauth2:
    client:
      client-id: UserManagement
      client-secret: user123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-validity-seconds: 15
      refresh-token-validity-seconds: 30
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
spring:
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false